# Generated by Django 3.1.7 on 2021-04-13 22:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200)),
                (
                    'description',
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 'active'),
                            (2, 'in_progress'),
                            (3, 'finished'),
                        ],
                        db_index=True,
                        default=1,
                        verbose_name='Task status',
                    ),
                ),
                (
                    'time_entries',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.DateTimeField(
                                blank=True, null=True
                            ),
                            size=2,
                        ),
                        size=None,
                    ),
                ),
            ],
        ),
    ]
