# Generated by Django 3.1.7 on 2021-04-13 23:07

import django.contrib.postgres.fields
from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_entries',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.DateTimeField(blank=True, null=True),
                    size=2,
                ),
                default=tracker.models.get_time_entries_default,
                size=None,
            ),
        ),
    ]
